export const data = {
  1: [
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
  ],
  2: [
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
  ],
  3: [
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
    { sorag: "4 + 5 = ", jogap: 9 },
    { sorag: "5 * 9 = ", jogap: 45 },
  ],
};
